name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand the problem you're solving.
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the limitation or gap you're facing.
      placeholder: "When generating docs for [type of project], I can't..."
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type of improvement
      options:
        - New command (slash command)
        - New skill (reference knowledge)
        - Template improvement (better generated output)
        - New doc type support
        - Upstream spec tracking
        - Other
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any workarounds?
